name: Linux Container Node Workflow

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: text2ascii.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t text2ascii.azurecr.io/text2ascii:${{ github.sha }}
        docker push text2ascii.azurecr.io/text2ascii:${{ github.sha }}    

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'text2ascii'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'text2ascii.azurecr.io/text2ascii:${{ github.sha }}'